#!/bin/bash

# Set the error handling flags
set -euo pipefail


# Trap errors and call cleanup function
trap 'echo "An error occurred. Exiting..."; exit 1;' ERR

# Start the main script
chroot "$LFS" /usr/bin/env -i \
    HOME=/root \
    TERM="$TERM" \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin \
    MAKEFLAGS="-j$(nproc)" \
    TESTSUITEFLAGS="-j$(nproc)" \
    /bin/bash --login << "EOF"
    set -euo pipefail

    source /etc/info.txt
    # Trap errors and call cleanup function
    trap 'echo "An error occurred. Exiting..."; exit 1;' ERR

    cd /sources

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                              XML::Parser-2.47                                 #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf XML-Parser-2.47.tar.gz

#     cd XML-Parser-2.47

#     perl Makefile.PL

#     make

#     # make test

#     make install

#     cd /sources

#     rm -rf XML-Parser-2.47

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                              Intltool-0.51.0                                  #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf intltool-0.51.0.tar.gz

#     cd intltool-0.51.0

#     sed -i 's:\\\${:\\\$\\{:' intltool-update.in

#     ./configure --prefix=/usr

#     make

#     # make check

#     make install
#     install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-0.51.0/I18N-HOWTO

#     cd /sources

#     rm -rf intltool-0.51.0

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                                Autoconf-2.72                                  #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf autoconf-2.72.tar.xz

#     cd autoconf-2.72

#     ./configure --prefix=/usr

#     make

#     # make check

#     make install

#     cd /sources

#     rm -rf autoconf-2.72

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                              Automake-1.16.5                                  #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf automake-1.16.5.tar.xz

#     cd automake-1.16.5

#     ./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.16.5

#     make

#     # make -j$(($(nproc)>4?$(nproc):4)) check

#     make install

#     cd /sources

#     rm -rf automake-1.16.5

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                               OpenSSL-3.2.1                                   #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf openssl-3.2.1.tar.gz

#     cd openssl-3.2.1

#     ./config --prefix=/usr         \
#             --openssldir=/etc/ssl \
#             --libdir=lib          \
#             shared                \
#             zlib-dynamic

#     make

#     HARNESS_JOBS=$(nproc) make test

#     sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
#     make MANSUFFIX=ssl install

#     mv -v /usr/share/doc/openssl /usr/share/doc/openssl-3.2.1

#     cp -vfr doc/* /usr/share/doc/openssl-3.2.1

#     cd /sources

#     rm -rf openssl-3.2.1

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                                   Kmod-31                                     #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf kmod-31.tar.xz

#     cd kmod-31

#     ./configure --prefix=/usr          \
#                 --sysconfdir=/etc      \
#                 --with-openssl         \
#                 --with-xz              \
#                 --with-zstd            \
#                 --with-zlib

#     make

#     make install

#     for target in depmod insmod modinfo modprobe rmmod; do
#     ln -sfv ../bin/kmod /usr/sbin/$target
#     done

#     ln -sfv kmod /usr/bin/lsmod

#     cd /sources

#     rm -rf kmod-31

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                       Libelf from Elfutils-0.190                              #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf elfutils-0.190.tar.bz2

#     cd elfutils-0.190

#     ./configure --prefix=/usr                \
#                 --disable-debuginfod         \
#                 --enable-libdebuginfod=dummy

#     make

#     # make check

#     make -C libelf install
#     install -vm644 config/libelf.pc /usr/lib/pkgconfig
#     rm /usr/lib/libelf.a

#     cd /sources

#     rm -rf elfutils-0.190

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                                Libffi-3.4.4                                   #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf libffi-3.4.4.tar.gz

#     cd libffi-3.4.4

#     ./configure --prefix=/usr          \
#                 --disable-static       \
#                 --with-gcc-arch=native

#     make

#     # make check

#     make install

#     cd /sources

#     rm -rf libffi-3.4.4

#     echo "#-------------------------------------------------------------------------------#"
#     echo "#                               Python-3.12.2                                   #"
#     echo "#-------------------------------------------------------------------------------#"

#     tar -xvf Python-3.12.2.tar.xz

#     cd Python-3.12.2

#     ./configure --prefix=/usr        \
#                 --enable-shared      \
#                 --with-system-expat  \
#                 --enable-optimizations

#     make

#     make install

#     cat > /etc/pip.conf << "PIP_EOF"
# [global]
# root-user-action = ignore
# disable-pip-version-check = true
# PIP_EOF

# install -v -dm755 /usr/share/doc/python-3.12.2/html

# tar --no-same-owner \
# -xvf ../python-3.12.2-docs-html.tar.bz2
# cp -R --no-preserve=mode python-3.12.2-docs-html/* \
# /usr/share/doc/python-3.12.2/html

# cd /sources

# rm -rf Python-3.12.2

# echo "#-------------------------------------------------------------------------------#"
# echo "#                              Flit-Core-3.9.0                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf flit_core-3.9.0.tar.gz

# cd flit_core-3.9.0

# pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

# pip3 install --no-index --no-user --find-links dist flit_core

# cd /sources

# rm -rf flit_core-3.9.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                  Wheel-0.42.0                                 #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf wheel-0.42.0.tar.gz

# cd wheel-0.42.0

# pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

# pip3 install --no-index --find-links=dist wheel


# cd /sources

# rm -rf wheel-0.42.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                              Setuptools-69.1.0                                #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf setuptools-69.1.0.tar.gz

# cd setuptools-69.1.0

# pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

# pip3 install --no-index --find-links dist setuptools

# cd /sources

# rm -rf setuptools-69.1.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Ninja-1.11.1                                   #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf ninja-1.11.1.tar.gz

# cd ninja-1.11.1

# export NINJAJOBS=10

# sed -i '/int Guess/a \
#     int   j = 0;\
#     char* jobs = getenv( "NINJAJOBS" );\
#     if ( jobs != NULL ) j = atoi( jobs );\
#     if ( j > 0 ) return j;\
# ' src/ninja.cc

# python3 configure.py --bootstrap

# ./ninja ninja_test
# ./ninja_test --gtest_filter=-SubprocessTest.SetWithLots

# install -vm755 ninja /usr/bin/
# install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja
# install -vDm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja

# cd /sources

# rm -rf ninja-1.11.1

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                 Meson-1.3.2                                   #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf meson-1.3.2.tar.gz

# cd meson-1.3.2

# pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

# pip3 install --no-index --find-links dist meson
# install -vDm644 data/shell-completions/bash/meson /usr/share/bash-completion/completions/meson
# install -vDm644 data/shell-completions/zsh/_meson /usr/share/zsh/site-functions/_meson

# cd /sources

# rm -rf meson-1.3.2

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Coreutils-9.4                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf coreutils-9.4.tar.xz

# cd coreutils-9.4

# patch -Np1 -i ../coreutils-9.4-i18n-1.patch

# autoreconf -fiv
# FORCE_UNSAFE_CONFIGURE=1 ./configure \
# --prefix=/usr            \
# --enable-no-install-program=kill,uptime

# make

# # make NON_ROOT_USERNAME=tester check-root

# # groupadd -g 102 dummy -U tester

# # chown -R tester .

# # su tester -c "PATH=$PATH make RUN_EXPENSIVE_TESTS=yes check"

# # groupdel dummy

# make install

# mv -v /usr/bin/chroot /usr/sbin
# mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
# sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8

# cd /sources

# rm -rf coreutils-9.4

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Check-0.15.2                                   #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf check-0.15.2.tar.gz

# cd check-0.15.2

# ./configure --prefix=/usr --disable-static

# make

# # make check

# # make docdir=/usr/share/doc/check-0.15.2 install

# cd /sources

# rm -rf check-0.15.2

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Diffutils-3.10                                 #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf diffutils-3.10.tar.xz

# cd diffutils-3.10

# ./configure --prefix=/usr

# make

# # make check

# make install

# cd /sources

# rm -rf diffutils-3.10

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                  Gawk-5.3.0                                   #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf gawk-5.3.0.tar.xz

# cd gawk-5.3.0

# sed -i 's/extras//' Makefile.in

# ./configure --prefix=/usr

# make

# # chown -R tester .
# # su tester -c "PATH=$PATH make check"

# rm -f /usr/bin/gawk-5.3.0
# make install

# ln -sv gawk.1 /usr/share/man/man1/awk.1

# mkdir -pv                                   /usr/share/doc/gawk-5.3.0
# cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-5.3.0

# cd /sources

# rm -rf gawk-5.3.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                              Findutils-4.9.0                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf findutils-4.9.0.tar.xz

# cd findutils-4.9.0

# ./configure --prefix=/usr --localstatedir=/var/lib/locate

# make

# # chown -R tester .
# # su tester -c "PATH=$PATH make check"

# make install

# cd /sources

# rm -rf findutils-4.9.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                 Groff-1.23.0                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf groff-1.23.0.tar.gz

# cd groff-1.23.0

# PAGE=A4 ./configure --prefix=/usr

# make

# # make check

# make install

# cd /sources

# rm -rf groff-1.23.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                 Which-2.21                                    #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf which-2.21.tar.gz

# cd which-2.21

# ./configure --prefix=/usr &&
# make

# make install

# cd /sources

# rm -rf which-2.21

# echo "#-------------------------------------------------------------------------------#"
# echo "#                               Libpng-1.6.42                                   #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf libpng-1.6.42.tar.xz

# cd libpng-1.6.42

# gzip -cd ../libpng-1.6.40-apng.patch.gz | patch -p1

# ./configure --prefix=/usr --disable-static &&
# make

# make install &&
# mkdir -v /usr/share/doc/libpng-1.6.42 &&
# cp -v README libpng-manual.txt /usr/share/doc/libpng-1.6.42

# cd /sources

# rm -rf libpng-1.6.42

# echo "#-------------------------------------------------------------------------------#"
# echo "#                              Freetype-2.13.2                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf freetype-2.13.2.tar.xz

# cd freetype-2.13.2

# tar -xf ../freetype-doc-2.13.2.tar.xz --strip-components=2 -C docs

# sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg &&

# sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
# -i include/freetype/config/ftoption.h  &&

# ./configure --prefix=/usr --enable-freetype-config --disable-static &&
# make



# make install

# cp -v -R docs -T /usr/share/doc/freetype-2.13.2 &&
# rm -v /usr/share/doc/freetype-2.13.2/freetype-config.1

# cd /sources

# rm -rf freetype-2.13.2

# echo "#-------------------------------------------------------------------------------#"
# echo "#                              Harfbuzz-8.3.0                                   #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf harfbuzz-8.3.0.tar.xz

# cd harfbuzz-8.3.0

# mkdir build && cd build
# meson setup .. --prefix=/usr --buildtype=release
# ninja -v

# ninja install

# cd /sources

# rm -rf harfbuzz-8.3.0

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                 Popt-1.19                                     #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf popt-1.19.tar.gz

# cd popt-1.19

# ./configure --prefix=/usr --disable-static &&
# make

# make install

# cd /sources

# rm -rf popt-1.19

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Mandoc-1.14.6                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf mandoc-1.14.6.tar.gz

# cd mandoc-1.14.6

# ./configure &&
# make mandoc

# install -vm755 mandoc   /usr/bin &&
# install -vm644 mandoc.1 /usr/share/man/man1

# cd /sources

# rm -rf mandoc-1.14.6

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Efivar-39                                      #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf efivar-39.tar.gz

# cd efivar-39

# make

# make install LIBDIR=/usr/lib

# cd /sources

# rm -rf efivar-39.tar.gz

# echo "#-------------------------------------------------------------------------------#"
# echo "#                                Efibootmgr-18                                  #"
# echo "#-------------------------------------------------------------------------------#"

# tar -xvf efibootmgr-18.tar.gz

# cd efibootmgr-18

# make EFIDIR=LFS EFI_LOADER=grubx64.efi

# make install EFIDIR=LFS

# cd /sources

# rm -rf efibootmgr-18

echo "#-------------------------------------------------------------------------------#"
echo "#                                 GRUB-2.12                                     #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf grub-2.12.tar.xz

cd grub-2.12

mkdir -pv /usr/share/fonts/unifont &&
gunzip -c ../unifont-15.1.04.pcf.gz > /usr/share/fonts/unifont/unifont.pcf

unset {C,CPP,CXX,LD}FLAGS

echo depends bli part_gpt > grub-core/extra_deps.lst

./configure --prefix=/usr        \
--sysconfdir=/etc    \
--disable-efiemu     \
--enable-grub-mkfont \
--with-platform=efi  \
--target=x86_64      \
--disable-werror     &&
unset TARGET_CC &&
make

make install &&
mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions

cd /sources

rm -rf grub-2.12.tar.xz

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Gzip-1.13                                     #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf gzip-1.13.tar.xz

cd gzip-1.13

./configure --prefix=/usr

make

# make check

make install

cd /sources

rm -rf gzip-1.13

echo "#-------------------------------------------------------------------------------#"
echo "#                              IPRoute2-6.7.0                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf iproute2-6.7.0.tar.xz

cd iproute2-6.7.0

sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8

make NETNS_RUN_DIR=/run/netns

make SBINDIR=/usr/sbin install

mkdir -pv             /usr/share/doc/iproute2-6.7.0
cp -v COPYING README* /usr/share/doc/iproute2-6.7.0

cd /sources

rm -rf  iproute2-6.7.0

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Kbd-2.6.4                                     #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf kbd-2.6.4.tar.xz

cd kbd-2.6.4

patch -Np1 -i ../kbd-2.6.4-backspace-1.patch

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

./configure --prefix=/usr --disable-vlock

make

# make check

make install

cp -R -v docs/doc -T /usr/share/doc/kbd-2.6.4

cd /sources

rm -rf kbd-2.6.4

echo "#-------------------------------------------------------------------------------#"
echo "#                              Libpipeline-1.5.7                                #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf libpipeline-1.5.7.tar.gz

cd libpipeline-1.5.7

./configure --prefix=/usr

make

# make check

make install

cd /sources

rm -rf libpipeline-1.5.7

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Make-4.4.1                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf make-4.4.1.tar.gz

cd make-4.4.1

./configure --prefix=/usr

make

# chown -R tester .
# su tester -c "PATH=$PATH make check"

make install

cd /sources

rm -rf make-4.4.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Patch-2.7.6                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf patch-2.7.6.tar.xz

cd patch-2.7.6

./configure --prefix=/usr

make

make install

cd /sources

rm -rf patch-2.7.6

echo "#-------------------------------------------------------------------------------#"
echo "#                                   Tar-1.35                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf tar-1.35.tar.xz

cd tar-1.35

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr

make

make install
make -C doc install-html docdir=/usr/share/doc/tar-1.35

cd /sources

rm -rf tar-1.35

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Texinfo-7.1                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf texinfo-7.1.tar.xz

cd texinfo-7.1

./configure --prefix=/usr

make

make install

make TEXMF=/usr/share/texmf install-tex

cd /sources

rm -rf texinfo-7.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                Vim-9.1.0041                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf vim-9.1.0041.tar.gz

cd vim-9.1.0041

echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

./configure --prefix=/usr

make

# chown -R tester .

# su tester -c "TERM=xterm-256color LANG=en_US.UTF-8 make -j1 test" \
#    &> vim-test.log

make install

ln -sv vim /usr/bin/vi
for L in  /usr/share/man/{,*/}man1/vim.1; do
    ln -sv vim.1 $(dirname $L)/vi.1
done

ln -sv ../vim/vim91/doc /usr/share/doc/vim-9.1.0041

    cat > /etc/vimrc << "VIM_EOF"
" Begin /etc/vimrc

" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim
let skip_defaults_vim=1

set nocompatible
set backspace=2
set mouse=
syntax on
if (&term == "xterm") || (&term == "putty")
    set background=dark
endif

" End /etc/vimrc
VIM_EOF

cd /sources

rm -rf vim-9.1.0041

echo "#-------------------------------------------------------------------------------#"
echo "#                              MarkupSafe-2.1.5                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf MarkupSafe-2.1.5.tar.gz

cd MarkupSafe-2.1.5

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --no-user --find-links dist Markupsafe

cd /sources

rm -rf MarkupSafe-2.1.5

echo "#-------------------------------------------------------------------------------#"
echo "#                                Jinja2-3.1.3                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf Jinja2-3.1.3.tar.gz

cd Jinja2-3.1.3

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --no-user --find-links dist Jinja2

cd /sources

rm -rf Jinja2-3.1.3

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Systemd-255                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf systemd-255.tar.gz

cd systemd-255

sed -i -e 's/GROUP="render"/GROUP="video"/' \
-e 's/GROUP="sgx", //' rules.d/50-udev-default.rules.in

patch -Np1 -i ../systemd-255-upstream_fixes-1.patch

mkdir -p build
cd       build

meson setup \
--prefix=/usr                 \
--buildtype=release           \
-Ddefault-dnssec=no           \
-Dfirstboot=false             \
-Dinstall-tests=false         \
-Dldconfig=false              \
-Dsysusers=false              \
-Drpmmacrosdir=no             \
-Dhomed=disabled              \
-Duserdb=false                \
-Dman=disabled                \
-Dmode=release                \
-Dpamconfdir=no               \
-Ddev-kvm-mode=0660           \
-Dnobody-group=nogroup        \
-Dsysupdate=disabled          \
-Dukify=disabled              \
-Ddocdir=/usr/share/doc/systemd-255 \
..

ninja

ninja install

tar -xf ../../systemd-man-pages-255.tar.xz \
--no-same-owner --strip-components=1   \
-C /usr/share/man

systemd-machine-id-setup

systemctl preset-all

cd /sources

rm -rf systemd-255

echo "#-------------------------------------------------------------------------------#"
echo "#                                D-Bus-1.14.10                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf dbus-1.14.10.tar.xz

cd dbus-1.14.10

./configure --prefix=/usr                        \
--sysconfdir=/etc                    \
--localstatedir=/var                 \
--runstatedir=/run                   \
--enable-user-session                \
--disable-static                     \
--disable-doxygen-docs               \
--disable-xml-docs                   \
--docdir=/usr/share/doc/dbus-1.14.10 \
--with-system-socket=/run/dbus/system_bus_socket

make

# make check

make install

ln -sfv /etc/machine-id /var/lib/dbus

cd /sources

rm -rf dbus-1.14.10

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Man-DB-2.12.0                                #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf man-db-2.12.0.tar.xz

cd man-db-2.12.0

./configure --prefix=/usr                         \
--docdir=/usr/share/doc/man-db-2.12.0 \
--sysconfdir=/etc                     \
--disable-setuid                      \
--enable-cache-owner=bin              \
--with-browser=/usr/bin/lynx          \
--with-vgrind=/usr/bin/vgrind         \
--with-grap=/usr/bin/grap             \
--with-systemdtmpfilesdir=            \
--with-systemdsystemunitdir=

make

make install

cd /sources

rm -rf man-db-2.12.0

echo "#-------------------------------------------------------------------------------#"
echo "#                              Procps-ng-4.0.4                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf procps-ng-4.0.4.tar.xz

cd procps-ng-4.0.4

./configure --prefix=/usr                           \
--docdir=/usr/share/doc/procps-ng-4.0.4 \
--disable-static                        \
--disable-kill                          \
--with-systemd

make src_w_LDADD='$(LDADD) -lsystemd'

# make -k check

make install
cd /sources

rm -rf procps-ng-4.0.4

echo "#-------------------------------------------------------------------------------#"
echo "#                              Util-linux-2.39.3                                #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf util-linux-2.39.3.tar.xz

cd util-linux-2.39.3

sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am

./configure --bindir=/usr/bin    \
--libdir=/usr/lib    \
--runstatedir=/run   \
--sbindir=/usr/sbin  \
--disable-chfn-chsh  \
--disable-login      \
--disable-nologin    \
--disable-su         \
--disable-setpriv    \
--disable-runuser    \
--disable-pylibmount \
--disable-static     \
--without-python     \
ADJTIME_PATH=/var/lib/hwclock/adjtime \
--docdir=/usr/share/doc/util-linux-2.39.3
make
make install

cd /sources

rm -rf util-linux-2.39.3

echo "#-------------------------------------------------------------------------------#"
echo "#                              E2fsprogs-1.47.0                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf e2fsprogs-1.47.0.tar.gz

cd e2fsprogs-1.47.0

mkdir -v build
cd       build

../configure --prefix=/usr           \
--sysconfdir=/etc       \
--enable-elf-shlibs     \
--disable-libblkid      \
--disable-libuuid       \
--disable-uuidd         \
--disable-fsck
make

make install

rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a

gunzip -v /usr/share/info/libext2fs.info.gz
install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info

makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
install -v -m644 doc/com_err.info /usr/share/info
install-info --dir-file=/usr/share/info/dir /usr/share/info/com_err.info

cd /sources

rm -rf e2fsprogs-1.47.0

echo "#-------------------------------------------------------------------------------#"
echo "#                                Cleaning Up                                    #"
echo "#-------------------------------------------------------------------------------#"

rm -rf /tmp/*
find /usr/lib /usr/libexec -name \*.la -delete
find /usr -depth -name $(uname -m)-lfs-linux-gnu\* | xargs rm -rf

EOF
