#!/bin/bash

# Set the error handling flags
set -euo pipefail


# Trap errors and call cleanup function
trap 'echo "An error occurred. Exiting..."; exit 1;' ERR

cp $Info $LFS/etc
# Start the main script
chroot "$LFS" /usr/bin/env -i \
    HOME=/root \
    TERM="$TERM" \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin \
    MAKEFLAGS="-j$(nproc)" \
    TESTSUITEFLAGS="-j$(nproc)" \
    /bin/bash --login << "EOF"
    set -euo pipefail


    # Trap errors and call cleanup function
    trap 'echo "An error occurred. Exiting..."; exit 1;' ERR
    source /etc/info.txt
    cd /sources

    echo "#-------------------------------------------------------------------------------#"
    echo "#                               Man-pages-6.06                                  #"
    echo "#-------------------------------------------------------------------------------#"

    tar -xvf man-pages-6.06.tar.xz
    cd man-pages-6.06
    rm -v man3/crypt*
    make prefix=/usr install
    cd /sources
    rm -rf man-pages-6.06

    echo "#-------------------------------------------------------------------------------#"
    echo "#                              Iana-Etc-20240125                                #"
    echo "#-------------------------------------------------------------------------------#"

    tar -xvf iana-etc-20240125.tar.gz
    cd iana-etc-20240125
    cp services protocols /etc
    cd /sources
    rm -rf iana-etc-20240125

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                  Glibc-2.39                                   #"
    echo "#-------------------------------------------------------------------------------#"

    tar -xvf glibc-2.39.tar.xz
    cd glibc-2.39
    patch -Np1 -i ../glibc-2.39-fhs-1.patch
    mkdir -v build
    cd build

    echo "rootsbindir=/usr/sbin" > configparms
    ../configure --prefix=/usr \
                 --disable-werror \
                 --enable-kernel=4.19 \
                 --enable-stack-protector=strong \
                 --disable-nscd \
                 libc_cv_slibdir=/usr/lib
    make
    touch /etc/ld.so.conf

    sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

    mkdir -pv /usr/lib/locale
    localedef -i C -f UTF-8 C.UTF-8
    localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
    localedef -i de_DE -f ISO-8859-1 de_DE
    localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
    localedef -i de_DE -f UTF-8 de_DE.UTF-8
    localedef -i el_GR -f ISO-8859-7 el_GR
    localedef -i en_GB -f ISO-8859-1 en_GB
    localedef -i en_GB -f UTF-8 en_GB.UTF-8
    localedef -i en_HK -f ISO-8859-1 en_HK
    localedef -i en_PH -f ISO-8859-1 en_PH
    localedef -i en_US -f ISO-8859-1 en_US
    localedef -i en_US -f UTF-8 en_US.UTF-8
    localedef -i es_ES -f ISO-8859-15 es_ES@euro
    localedef -i es_MX -f ISO-8859-1 es_MX
    localedef -i fa_IR -f UTF-8 fa_IR
    localedef -i fr_FR -f ISO-8859-1 fr_FR
    localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
    localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
    localedef -i is_IS -f ISO-8859-1 is_IS
    localedef -i is_IS -f UTF-8 is_IS.UTF-8
    localedef -i it_IT -f ISO-8859-1 it_IT
    localedef -i it_IT -f ISO-8859-15 it_IT@euro
    localedef -i it_IT -f UTF-8 it_IT.UTF-8
    localedef -i ja_JP -f EUC-JP ja_JP
    localedef -i ja_JP -f SHIFT_JIS ja_JP.SJIS 2> /dev/null || true
    localedef -i ja_JP -f UTF-8 ja_JP.UTF-8
    localedef -i nl_NL@euro -f ISO-8859-15 nl_NL@euro
    localedef -i ru_RU -f KOI8-R ru_RU.KOI8-R
    localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
    localedef -i se_NO -f UTF-8 se_NO.UTF-8
    localedef -i ta_IN -f UTF-8 ta_IN.UTF-8
    localedef -i tr_TR -f UTF-8 tr_TR.UTF-8
    localedef -i zh_CN -f GB18030 zh_CN.GB18030
    localedef -i zh_HK -f BIG5-HKSCS zh_HK.BIG5-HKSCS
    localedef -i zh_TW -f UTF-8 zh_TW.UTF-8

    make localedata/install-locales

    localedef -i C -f UTF-8 C.UTF-8
    localedef -i ja_JP -f SHIFT_JIS ja_JP.SJIS 2> /dev/null || true

    cat > /etc/nsswitch.conf << "NS_EOF"
# Begin /etc/nsswitch.conf

passwd: files systemd
group: files systemd
shadow: files systemd

hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
NS_EOF

tar -xf ../../tzdata2024a.tar.gz

ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica \
asia australasia backward; do
    zic -L /dev/null   -d $ZONEINFO       ${tz}
    zic -L /dev/null   -d $ZONEINFO/posix ${tz}
    zic -L leapseconds -d $ZONEINFO/right ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

ln -sfv /usr/share/zoneinfo/$timezone /etc/localtime

    cat > /etc/ld.so.conf << "LD_EOF"
    # Begin /etc/ld.so.conf
    /usr/local/lib
    /opt/lib

# End /etc/ld.so.conf
LD_EOF

cd /sources
rm -rf glibc-2.39

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Zlib-1.3.1                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf zlib-1.3.1.tar.gz
cd zlib-1.3.1
./configure --prefix=/usr
make
# make check
make install
rm -fv /usr/lib/libz.a
cd /sources
rm -rf zlib-1.3.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Bzip2-1.0.8                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf bzip2-1.0.8.tar.gz
cd bzip2-1.0.8
patch -Np1 -i ../bzip2-1.0.8-install_docs-1.patch
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile
make -f Makefile-libbz2_so
make clean
make
make PREFIX=/usr install
cp -av libbz2.so.* /usr/lib
ln -sv libbz2.so.1.0.8 /usr/lib/libbz2.so
cp -v bzip2-shared /usr/bin/bzip2
for i in /usr/bin/{bzcat,bunzip2}; do
    ln -sfv bzip2 $i
done
rm -fv /usr/lib/libbz2.a
cd /sources
rm -rf bzip2-1.0.8

echo "#-------------------------------------------------------------------------------#"
echo "#                                   Xz-5.4.6                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf xz-5.4.6.tar.xz
cd xz-5.4.6
./configure --prefix=/usr \
--disable-static \
--docdir=/usr/share/doc/xz-5.4.6
make
# make check
make install
cd /sources
rm -rf xz-5.4.6

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Zstd-1.5.5                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf zstd-1.5.5.tar.gz
cd zstd-1.5.5
make prefix=/usr
# make check
make prefix=/usr install
rm -v /usr/lib/libzstd.a
cd /sources/
rm -rf zstd-1.5.5

echo "#-------------------------------------------------------------------------------#"
echo "#                                   File-5.45                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf file-5.45.tar.gz
cd file-5.45
./configure --prefix=/usr
make
# make check
make install
cd /sources/
rm -rf file-5.45

echo "#-------------------------------------------------------------------------------#"
echo "#                                Readline-8.2                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf readline-8.2.tar.gz
cd readline-8.2
sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install
patch -Np1 -i ../readline-8.2-upstream_fixes-3.patch
./configure --prefix=/usr \
--disable-static \
--with-curses \
--docdir=/usr/share/doc/readline-8.2
make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" install
install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.2
cd /sources
rm -rf readline-8.2

echo "#-------------------------------------------------------------------------------#"
echo "#                                   M4-1.4.19                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf m4-1.4.19.tar.xz
cd m4-1.4.19
./configure --prefix=/usr
make
# make check
make install
cd /sources
rm -rf m4-1.4.19

echo "#-------------------------------------------------------------------------------#"
echo "#                                   Bc-6.7.5                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf bc-6.7.5.tar.xz
cd bc-6.7.5
CC=gcc ./configure --prefix=/usr -G -O3 -r
make
# make test
make install
cd /sources/
rm -rf bc-6.7.5

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Flex-2.6.4                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf flex-2.6.4.tar.gz
cd flex-2.6.4
./configure --prefix=/usr \
--docdir=/usr/share/doc/flex-2.6.4 \
--disable-static
make
# make check
make install
ln -sv flex /usr/bin/lex
ln -sv flex.1 /usr/share/man/man1/lex.1
cd /sources
rm -rf flex-2.6.4

echo "#-------------------------------------------------------------------------------#"
echo "#                                   Tcl-8.6.13                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf tcl8.6.13-src.tar.gz

cd tcl8.6.13

SRCDIR=$(pwd)
cd unix
./configure --prefix=/usr           \
--mandir=/usr/share/man

make

sed -e "s|$SRCDIR/unix|/usr/lib|" \
-e "s|$SRCDIR|/usr/include|"  \
-i tclConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.5|/usr/lib/tdbc1.1.5|" \
-e "s|$SRCDIR/pkgs/tdbc1.1.5/generic|/usr/include|"    \
-e "s|$SRCDIR/pkgs/tdbc1.1.5/library|/usr/lib/tcl8.6|" \
-e "s|$SRCDIR/pkgs/tdbc1.1.5|/usr/include|"            \
-i pkgs/tdbc1.1.5/tdbcConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/itcl4.2.3|/usr/lib/itcl4.2.3|" \
-e "s|$SRCDIR/pkgs/itcl4.2.3/generic|/usr/include|"    \
-e "s|$SRCDIR/pkgs/itcl4.2.3|/usr/include|"            \
-i pkgs/itcl4.2.3/itclConfig.sh

unset SRCDIR

# make test

make install

chmod -v u+w /usr/lib/libtcl8.6.so

make install-private-headers

ln -sfv tclsh8.6 /usr/bin/tclsh

mv /usr/share/man/man3/{Thread,Tcl_Thread}.3

cd ..
tar -xf ../tcl8.6.13-html.tar.gz --strip-components=1
mkdir -v -p /usr/share/doc/tcl-8.6.13
cp -v -r  ./html/* /usr/share/doc/tcl-8.6.13

cd /sources

rm -rf tcl8.6.13

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Expect-5.45.4                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf expect5.45.4.tar.gz

cd expect5.45.4

./configure --prefix=/usr           \
--with-tcl=/usr/lib     \
--enable-shared         \
--mandir=/usr/share/man \
--with-tclinclude=/usr/include

make

# make test

make install
ln -svf expect5.45.4/libexpect5.45.4.so /usr/lib

cd /sources

rm -rf expect5.45.4

echo "#-------------------------------------------------------------------------------#"
echo "#                                DejaGNU-1.6.3                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf dejagnu-1.6.3.tar.gz

cd dejagnu-1.6.3

mkdir -v build
cd       build

../configure --prefix=/usr
makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi
makeinfo --plaintext       -o doc/dejagnu.txt  ../doc/dejagnu.texi

# make check

make install
install -v -dm755  /usr/share/doc/dejagnu-1.6.3
install -v -m644   doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.3

cd /sources

rm -rf dejagnu-1.6.3

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Pkgconf-2.1.1                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf pkgconf-2.1.1.tar.xz

cd pkgconf-2.1.1

./configure --prefix=/usr              \
--disable-static           \
--docdir=/usr/share/doc/pkgconf-2.1.1

make

make install

ln -sv pkgconf   /usr/bin/pkg-config
ln -sv pkgconf.1 /usr/share/man/man1/pkg-config.1

cd /sources

rm -rf pkgconf-2.1.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                Binutils-2.42                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf binutils-2.42.tar.xz

cd binutils-2.42

mkdir -v build
cd       build

../configure --prefix=/usr       \
--sysconfdir=/etc   \
--enable-gold       \
--enable-ld=default \
--enable-plugins    \
--enable-shared     \
--disable-werror    \
--enable-64-bit-bfd \
--with-system-zlib  \
--enable-default-hash-style=gnu

make tooldir=/usr

# make -k check

# grep '^FAIL:' $(find -name '*.log')

make tooldir=/usr install

rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a

cd /sources

rm -rf binutils-2.42

echo "#-------------------------------------------------------------------------------#"
echo "#                                   GMP-6.3.0                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf gmp-6.3.0.tar.xz

cd gmp-6.3.0

./configure --prefix=/usr    \
--enable-cxx     \
--disable-static \
--docdir=/usr/share/doc/gmp-6.3.0

make
make html

make check 2>&1 | tee gmp-check-log

# Ensure that at least 199 tests in the test suite passed
if [ $(awk '/# PASS:/{total+=$3} ; END{print total}' gmp-check-log) -lt 199 ]; then
    echo "Less than 199 tests passed. Aborting."
    exit 1
fi

make install
make install-html

cd /sources

rm -rf gmp-6.3.0

echo "#-------------------------------------------------------------------------------#"
echo "#                                  MPFR-4.2.1                                   #"
echo "#-------------------------------------------------------------------------------#"


tar -xvf mpfr-4.2.1.tar.xz

cd mpfr-4.2.1

./configure --prefix=/usr        \
--disable-static     \
--enable-thread-safe \
--docdir=/usr/share/doc/mpfr-4.2.1

make
make html

make check 2>&1 | tee mpfr-check-log

# Ensure that all 198 tests passed
if [ $(awk '/# PASS:/{total+=$3} ; END{print total}' mpfr-check-log) -ne 198 ]; then
    echo "Not all 198 tests passed. Aborting."
    exit 1
fi

make install
make install-html

cd /sources

rm -rf mpfr-4.2.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                   MPC-1.3.1                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf mpc-1.3.1.tar.gz

cd mpc-1.3.1

./configure --prefix=/usr    \
--disable-static \
--docdir=/usr/share/doc/mpc-1.3.1

make
make html

# make check

make install
make install-html

cd /sources

rm -rf mpc-1.3.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Attr-2.5.2                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf attr-2.5.2.tar.gz

cd attr-2.5.2

./configure --prefix=/usr     \
--disable-static  \
--sysconfdir=/etc \
--docdir=/usr/share/doc/attr-2.5.2

make

# make check

make install

cd /sources

rm -rf attr-2.5.2

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Acl-2.3.2                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf acl-2.3.2.tar.xz

cd acl-2.3.2

./configure --prefix=/usr         \
--disable-static      \
--docdir=/usr/share/doc/acl-2.3.2

make

make install

cd /sources

rm -rf acl-2.3.2

echo "#-------------------------------------------------------------------------------#"
echo "#                                   Libcap-2.69                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf libcap-2.69.tar.xz

cd libcap-2.69

sed -i '/install -m.*STA/d' libcap/Makefile

make prefix=/usr lib=lib

# make test

make prefix=/usr lib=lib install

cd /sources

rm -rf libcap-2.69

echo "#-------------------------------------------------------------------------------#"
echo "#                               Libxcrypt-4.4.36                                #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf libxcrypt-4.4.36.tar.xz

cd libxcrypt-4.4.36

./configure --prefix=/usr                \
--enable-hashes=strong,glibc \
--enable-obsolete-api=no     \
--disable-static             \
--disable-failure-tokens

make

# make check

make install

cd /sources

rm -rf libxcrypt-4.4.36

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Shadow-4.14.5                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf shadow-4.14.5.tar.xz

cd shadow-4.14.5

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;

touch /usr/bin/passwd
./configure --sysconfdir=/etc   \
--disable-static    \
--with-{b,yes}crypt \
--without-libbsd    \
--with-group-name-max-length=32

make

make exec_prefix=/usr install
make -C man install-man

pwconv

grpconv

mkdir -p /etc/default
useradd -D --gid 999

echo "root:$PASSWORD" > /tmp/rootpasswd

cat /tmp/rootpasswd | chpasswd

rm /tmp/rootpasswd

cd /sources

rm -rf shadow-4.14.5


echo "#-------------------------------------------------------------------------------#"
echo "#                                   GCC-13.2.0                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf gcc-13.2.0.tar.xz

cd gcc-13.2.0

# Adjust gcc for x86_64
case $(uname -m) in
    x86_64)
        sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
    ;;
esac

# Create and move to the build directory
mkdir -v build
cd build

# Configure the build
../configure --prefix=/usr            \
LD=ld                    \
--enable-languages=c,c++ \
--enable-default-pie     \
--enable-default-ssp     \
--disable-multilib       \
--disable-bootstrap      \
--disable-fixincludes    \
--with-system-zlib

# Compile the package
make

# Install the package
make install

# Change ownership of the installed headers
chown -v -R root:root /usr/lib/gcc/$(gcc -dumpmachine)/13.2.0/include{,-fixed}

# Create symbolic links
ln -svr /usr/bin/cpp /usr/lib
ln -sv gcc.1 /usr/share/man/man1/cc.1
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/13.2.0/liblto_plugin.so /usr/lib/bfd-plugins/

# Optional test commands (uncomment if needed)
# echo 'int main(){}' > dummy.c
# cc dummy.c -v -Wl,--verbose &> dummy.log
# readelf -l a.out | grep ': /lib'
# grep -E -o '/usr/lib.*/S?crt[1in].*succeeded' dummy.log
# grep -B4 '^ /usr/include' dummy.log
# grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
# grep "/lib.*/libc.so.6 " dummy.log
# grep found dummy.log
# rm -v dummy.c a.out dummy.log

# Move gdb auto-load scripts
mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib

# Clean up source directory
cd /sources
rm -rf gcc-13.2.0

echo "#-------------------------------------------------------------------------------#"
echo "#                             Ncurses-6.4-20230520                              #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf ncurses-6.4-20230520.tar.xz

cd ncurses-6.4-20230520

./configure --prefix=/usr           \
--mandir=/usr/share/man \
--with-shared           \
--without-debug         \
--without-normal        \
--with-cxx-shared       \
--enable-pc-files       \
--enable-widec          \
--with-pkg-config-libdir=/usr/lib/pkgconfig

make

make DESTDIR=$PWD/dest install
install -vm755 dest/usr/lib/libncursesw.so.6.4 /usr/lib
rm -v  dest/usr/lib/libncursesw.so.6.4
sed -e 's/^#if.*XOPEN.*$/#if 1/' \
-i dest/usr/include/curses.h
cp -av dest/* /

for lib in ncurses form panel menu ; do
    ln -sfv lib${lib}w.so /usr/lib/lib${lib}.so
    ln -sfv ${lib}w.pc    /usr/lib/pkgconfig/${lib}.pc
done

ln -sfv libncursesw.so /usr/lib/libcurses.so


cp -v -R doc -T /usr/share/doc/ncurses-6.4-20230520

cd /sources

rm -rf ncurses-6.4-20230520

echo "#-------------------------------------------------------------------------------#"
echo "#                                   Sed-4.9                                     #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf sed-4.9.tar.xz

cd sed-4.9

./configure --prefix=/usr

make
make html

# chown -R tester .
# su tester -c "PATH=$PATH make check"

make install
install -d -m755           /usr/share/doc/sed-4.9
install -m644 doc/sed.html /usr/share/doc/sed-4.9

cd /sources

rm -rf sed-4.9

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Psmisc-23.6                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf psmisc-23.6.tar.xz

cd psmisc-23.6

./configure --prefix=/usr

make

# make check

make install

cd /sources

rm -rf psmisc-23.6

echo "#-------------------------------------------------------------------------------#"
echo "#                                Gettext-0.22.4                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf gettext-0.22.4.tar.xz

cd gettext-0.22.4

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.22.4

make

# make check

make install
chmod -v 0755 /usr/lib/preloadable_libintl.so

cd /sources

rm -rf gettext-0.22.4

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Bison-3.8.2                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf bison-3.8.2.tar.xz

cd bison-3.8.2

./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2

make

# make check

make install

cd /sources

rm -rf bison-3.8.2

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Grep-3.11                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf grep-3.11.tar.xz 

cd  grep-3.11

sed -i "s/echo/#echo/" src/egrep.sh

./configure --prefix=/usr

make

# make check

make install

cd /sources

rm -rf  grep-3.11

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Bash-5.2.21                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf bash-5.2.21.tar.gz

cd bash-5.2.21

patch -Np1 -i ../bash-5.2.21-upstream_fixes-1.patch

./configure --prefix=/usr             \
            --without-bash-malloc     \
            --with-installed-readline \
            --docdir=/usr/share/doc/bash-5.2.21

make

# chown -R tester .

# su -s /usr/bin/expect tester << "EOF"
# set timeout -1
# spawn make tests
# expect eof
# lassign [wait] _ _ _ value
# exit $value
# EOF

make install

cd /sources

rm -rf bash-5.2.21

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Libtool-2.4.7                                 #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf libtool-2.4.7.tar.xz 

cd libtool-2.4.7

./configure --prefix=/usr

make

# make -k check

make install

rm -fv /usr/lib/libltdl.a

cd /sources

rm -rf libtool-2.4.7

echo "#-------------------------------------------------------------------------------#"
echo "#                                  GDBM-1.23                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf gdbm-1.23.tar.gz

cd gdbm-1.23

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat

make

# make check

make install

cd /sources

rm -rf gdbm-1.23

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Gperf-3.1                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf gperf-3.1.tar.gz

cd gperf-3.1

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1

make

# make -j1 check

make install

cd /sources

rm -rf gperf-3.1

echo "#-------------------------------------------------------------------------------#"
echo "#                                Expat-2.6.0                                    #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf expat-2.6.0.tar.xz

cd expat-2.6.0

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-2.6.0

make

# make check

make install

install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.6.0

cd /sources

rm -rf expat-2.6.0

echo "#-------------------------------------------------------------------------------#"
echo "#                                Inetutils-2.5                                  #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf inetutils-2.5.tar.xz 

cd inetutils-2.5

./configure --prefix=/usr        \
            --bindir=/usr/bin    \
            --localstatedir=/var \
            --disable-logger     \
            --disable-whois      \
            --disable-rcp        \
            --disable-rexec      \
            --disable-rlogin     \
            --disable-rsh        \
            --disable-servers

make

# make check

make install

mv -v /usr/{,s}bin/ifconfig

cd /sources

rm -rf inetutils-2.5

echo "#-------------------------------------------------------------------------------#"
echo "#                                  Less-643                                     #"
echo "#-------------------------------------------------------------------------------#"

cd /sources

tar -xvf less-643.tar.gz

cd less-643
 
./configure --prefix=/usr --sysconfdir=/etc

make

# make check

make install

cd /sources

rm -rf less-643

echo "#-------------------------------------------------------------------------------#"
echo "#                                 Perl-5.38.2                                   #"
echo "#-------------------------------------------------------------------------------#"

tar -xvf perl-5.38.2.tar.xz

cd perl-5.38.2

export BUILD_ZLIB=False
export BUILD_BZIP2=0

sh Configure -des                                         \
             -Dprefix=/usr                                \
             -Dvendorprefix=/usr                          \
             -Dprivlib=/usr/lib/perl5/5.38/core_perl      \
             -Darchlib=/usr/lib/perl5/5.38/core_perl      \
             -Dsitelib=/usr/lib/perl5/5.38/site_perl      \
             -Dsitearch=/usr/lib/perl5/5.38/site_perl     \
             -Dvendorlib=/usr/lib/perl5/5.38/vendor_perl  \
             -Dvendorarch=/usr/lib/perl5/5.38/vendor_perl \
             -Dman1dir=/usr/share/man/man1                \
             -Dman3dir=/usr/share/man/man3                \
             -Dpager="/usr/bin/less -isR"                 \
             -Duseshrplib                                 \
             -Dusethreads

make

make install
unset BUILD_ZLIB BUILD_BZIP2

cd /sources

rm -rf perl-5.38.2

exit 0
EOF
