#!/bin/bash

# Set the error handling flags
set -euo pipefail


# Trap errors and call cleanup function
trap 'echo "An error occurred. Exiting..."; exit 1;' ERR

# Define LFS variable if not already set
LFS="${LFS:-/mnt/lfs}"

# Function to check and mount filesystems
mount_filesystems() {
    mkdir -pv $LFS/{dev,proc,sys,run} || exit 1
    mount -v --bind /dev $LFS/dev || exit 1
    mount -vt devpts devpts -o gid=5,mode=0620 $LFS/dev/pts || exit 1
    mount -vt proc proc $LFS/proc || exit 1
    mount -vt sysfs sysfs $LFS/sys || exit 1
    mount -vt tmpfs tmpfs $LFS/run || exit 1

    if [ -h $LFS/dev/shm ]; then
        install -v -d -m 1777 $LFS$(realpath /dev/shm)
    else
        mount -vt tmpfs -o nosuid,nodev tmpfs $LFS/dev/shm
    fi
}

# Function to create necessary directories and set up symbolic links
setup_directories() {
    chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
    case $(uname -m) in
        x86_64) chown -R root:root $LFS/lib64 ;;
    esac
    
    mkdir -pv $LFS/{boot,home,mnt,opt,srv}
    mkdir -pv $LFS/etc/{opt,sysconfig}
    mkdir -pv $LFS/lib/firmware
    mkdir -pv $LFS/media/{floppy,cdrom}
    mkdir -pv $LFS/usr/{,local/}{include,src}
    mkdir -pv $LFS/usr/local/{bin,lib,sbin}
    mkdir -pv $LFS/usr/{,local/}share/{color,dict,doc,info,locale,man}
    mkdir -pv $LFS/usr/{,local/}share/{misc,terminfo,zoneinfo}
    mkdir -pv $LFS/usr/{,local/}share/man/man{1..8}
    mkdir -pv $LFS/var/{cache,local,log,mail,opt,spool}
    mkdir -pv $LFS/var/lib/{color,misc,locate}

    ln -sfv /run $LFS/var/run
    ln -sfv /run/lock $LFS/var/lock

    install -dv -m 0750 $LFS/root
    install -dv -m 1777 $LFS/tmp $LFS/var/tmp
    ln -sv /proc/self/mounts $LFS/etc/mtab
    cat > $LFS/etc/hosts << EOF
127.0.0.1  localhost $(hostname)
::1        localhost
EOF
    cat > $LFS/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/usr/bin/false
systemd-journal-remote:x:74:74:systemd Journal Remote:/:/usr/bin/false
systemd-journal-upload:x:75:75:systemd Journal Upload:/:/usr/bin/false
systemd-network:x:76:76:systemd Network Management:/:/usr/bin/false
systemd-resolve:x:77:77:systemd Resolver:/:/usr/bin/false
systemd-timesync:x:78:78:systemd Time Synchronization:/:/usr/bin/false
systemd-coredump:x:79:79:systemd Core Dumper:/:/usr/bin/false
uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
systemd-oom:x:81:81:systemd Out Of Memory Daemon:/:/usr/bin/false
nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
EOF
    cat > $LFS/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
kvm:x:61:
systemd-journal-gateway:x:73:
systemd-journal-remote:x:74:
systemd-journal-upload:x:75:
systemd-network:x:76:
systemd-resolve:x:77:
systemd-timesync:x:78:
systemd-coredump:x:79:
uuidd:x:80:
systemd-oom:x:81:
wheel:x:97:
users:x:999:
nogroup:x:65534:
EOF
}

# Main script execution
mount_filesystems
setup_directories

chroot "$LFS" /usr/bin/env -i \
    HOME=/root \
    TERM="$TERM" \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin \
    MAKEFLAGS="-j$(nproc)" \
    TESTSUITEFLAGS="-j$(nproc)" \
    /bin/bash --login << "CHROOT_EOF"
    set -euo pipefail

    touch /var/log/{btmp,lastlog,faillog,wtmp}
    chgrp -v utmp /var/log/lastlog
    chmod -v 664  /var/log/lastlog
    chmod -v 600  /var/log/btmp

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                  Gettext-0.22.4                               #"
    echo "#-------------------------------------------------------------------------------#"
    cd /sources
    echo "Extracting Gettext"
    tar -xvf gettext-0.22.4.tar.xz
    cd gettext-0.22.4
    ./configure --disable-shared 
    make
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
    cd /sources
    rm -rf gettext-0.22.4

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                  Bison-3.8.2                                  #"
    echo "#-------------------------------------------------------------------------------#"

    echo "Extracting Bison"
    tar -xvf bison-3.8.2.tar.xz
    cd bison-3.8.2
    ./configure --prefix=/usr \
                --docdir=/usr/share/doc/bison-3.8.2
    make
    make install
    cd /sources
    rm -rf bison-3.8.2

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                    Perl-5.38.2                                #"
    echo "#-------------------------------------------------------------------------------#"

    echo "Extracting Perl"
    tar -xvf perl-5.38.2.tar.xz
    cd perl-5.38.2
    sh Configure -des                                        \
                 -Dprefix=/usr                               \
                 -Dvendorprefix=/usr                         \
                 -Duseshrplib                                \
                 -Dprivlib=/usr/lib/perl5/5.38/core_perl     \
                 -Darchlib=/usr/lib/perl5/5.38/core_perl     \
                 -Dsitelib=/usr/lib/perl5/5.38/site_perl     \
                 -Dsitearch=/usr/lib/perl5/5.38/site_perl    \
                 -Dvendorlib=/usr/lib/perl5/5.38/vendor_perl \
                 -Dvendorarch=/usr/lib/perl5/5.38/vendor_perl
    make
    make install
    cd /sources
    rm -rf perl-5.38.2

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                  Python-3.12.2                                #"
    echo "#-------------------------------------------------------------------------------#"

    echo "Extracting Python"
    tar -xvf Python-3.12.2.tar.xz
    cd Python-3.12.2
    ./configure --prefix=/usr   \
                --enable-shared \
                --without-ensurepip
    make
    make install
    cd /sources
    rm -rf Python-3.12.2

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                  Texinfo-7.1                                  #"
    echo "#-------------------------------------------------------------------------------#"

    echo "Extracting Texinfo"
    tar -xvf texinfo-7.1.tar.xz
    cd texinfo-7.1
    ./configure --prefix=/usr
    make
    make install
    cd /sources
    rm -rf texinfo-7.1

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                Util-linux-2.39.3                              #"
    echo "#-------------------------------------------------------------------------------#"

    echo "Extracting Util-linux"
    tar -xvf util-linux-2.39.3.tar.xz
    cd util-linux-2.39.3
    mkdir -pv /var/lib/hwclock
    ./configure --libdir=/usr/lib    \
                --runstatedir=/run   \
                --disable-chfn-chsh  \
                --disable-login      \
                --disable-nologin    \
                --disable-su         \
                --disable-setpriv    \
                --disable-runuser    \
                --disable-pylibmount \
                --disable-static     \
                --without-python     \
                ADJTIME_PATH=/var/lib/hwclock/adjtime \
                --docdir=/usr/share/doc/util-linux-2.39.3
    make
    make install
    cd /sources
    rm -rf util-linux-2.39.3

    echo "#-------------------------------------------------------------------------------#"
    echo "#                                  Cleaning up                                  #"
    echo "#-------------------------------------------------------------------------------#"

    rm -rf /usr/share/{info,man,doc}/*
    find /usr/{lib,libexec} -name \*.la -delete
    rm -rf /tools

    echo "Chroot environment setup completed successfully."
    exit 0
CHROOT_EOF
