#!/bin/bash

# List of scripts to run in order
scripts=(
    "1-Man-pages.sh"
    "2-Iana-Etc.sh"
    "3-Glibc.sh"
    "4-Zlib.sh"
    "5-Bzip2.sh"
    "6-Xz.sh"
    "7-Zstd.sh"
    "8-File.sh"
    "9-Readline.sh"
    "10-M4.sh"
    "11-Bc.sh"
    "12-Flex.sh"
    "13-Tcl.sh"
    "14-Expect.sh"
    "15-DejaGNU.sh"
    "16-Pkgconf.sh"
    "17-Binutils.sh"
    "18-GMP.sh"
    "19-MPFR.sh"
    "20-MPC.sh"
    "21-Attr.sh"
    "22-Acl.sh"
    "23-Libcap.sh"
    "24-Libxcrypt.sh"
    "25-Shadow.sh"
    "26-GCC.sh"
    "27-Ncurses.sh"
    "28-Sed.sh"
    "29-Psmisc.sh"
    "30-Gettext.sh"
    "31-Bison.sh"
    "32-Grep.sh"
    "33-Bash.sh"
    "34-Libtool.sh"
    "35-GDBM.sh"
    "36-Gperf.sh"
    "37-Expat.sh"
    "38-Inetutils.sh"
    "39-Less.sh"
    "40-Perl.sh"
    "41-XML.sh"
    "42-Intltool.sh"
    "43-Autoconf.sh"
    "44-Automake.sh"
    "45-OpenSSL.sh"
    "46-Kmod.sh"
    "47-Libelf.sh"
    "48-Libffi.sh"
    "49-Python.sh"
    "50-Flit-Core.sh"
    "51-Wheel.sh"
    "52-Setuptools.sh"
    "53-Ninja.sh"
    "54-Meson.sh"
    "55-Coreutils.sh"
    "56-Check.sh"
    "57-Diffutils.sh"
    "58-Gawk.sh"
    "59-Findutils.sh"
    "60-Groff.sh"
    "61-GRUB.sh"
    "62-Gzip.sh"
    "63-IPRoute.sh"
    "64-Kbd.sh"
    "65-Libpipeline.sh"
    "66-Make.sh"
    "67-Patch.sh"
    "68-Tar.sh"
    "69-Texinfo.sh"
    "70-Vim.sh"
    "71-MarkupSafe.sh"
    "72-Jinja2.sh"
    "73-Udev.sh"
    "74-Man-DB.sh"
    "75-Procps-ng.sh"
    "76-Util-linux.sh"
    "77-E2fsprogs.sh"
    "78-Sysklogd.sh"
    "79-Sysvinit.sh"
    "80-Cleaning-Up.sh"
)

# Loop through the array and execute each script
for script in "${scripts[@]}"; do
    echo "Running $script..."
   ./"$script" || exit
done

echo "All scripts have been executed."
